apiVersion: v1
kind: Pod
metadata:
  generateName: data-reader-
spec:
  volumes:
    - name: generic-data-static
      persistentVolumeClaim:
        claimName: generic-data-static
        readOnly: true
  containers:
    - name: writer
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "The files in the persistent volume and their contents:" &
          grep ^ /generic-data-static/*
          sleep 9999
      volumeMounts:
        - name: generic-data
          mountPath: /generic-data-static
