apiVersion: v1
kind: Pod
metadata:
  generateName: data-writer-
spec:
  volumes:
    - name: generic-data-static
      persistentVolumeClaim:
        claimName: generic-data-static
  containers:
    - name: writer
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "A writer pod wrote this." > /generic-data-static/${HOSTNAME} &
          echo "I can write to /generic-data-static/${HOSTNAME}."
          sleep 9999
      volumeMounts:
        - name: generic-data-static
          mountPath: /generic-data-static
