apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generic-data-static
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: generic-volume
