apiVersion: v1
kind: Service
metadata:
  name: grok-service-exposed-headless
  namespace: gok
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: grok
